module.exports = {
BASE_SYMBOL: "TON",
BASE_ADDRESS: "TON",
BASE_DECIMALS: 9,

TRADE_AMOUNT_TON: 10,

MIN_PROFIT_TON: 0.01,
MIN_TON_BACK_RATIO: 0.97,

DEX_FEE_RATE: 0.003,
GAS_BUFFER_TON: 0.05,
SERVICE_FEE_TON: 0.02
};
